### ISSUE TITLE
Nicknames for "Marhsall" are suspect

### ISSUE THREAD

**Issue by mdweaver** [historical-record-linking/matching-codes#1]
I am using the nicknames in your abeclean.ado file to link 1860 census records to military service records.

I found that in your code there are many seemingly unrelated "nicknames" and abbreviations that match to the name "marshall".

**Comment by alvarocalderon** [comment]
Hi. Sorry for the delay and thanks very much for the feedback. I will take a look later this week.

**Comment by historical-record-linking** [comment]
Thanks for pointing this out! abeclean.ado has now been updated to fix this issue.
